# Generated by Django 2.2.4 on 2020-02-02 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=300)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delegacion',
            fields=[
                ('idDelegacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('habilitado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('idDeporte', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Deportista',
            fields=[
                ('idDeportista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=6)),
                ('foto', models.CharField(max_length=250)),
                ('fechaNacimiento', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('idEntrenador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LugarNacimiento',
            fields=[
                ('idLugarNacimiento', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModadalidadDeporte',
            fields=[
                ('idModalidadDeporte', models.AutoField(primary_key=True, serialize=False)),
                ('nombreModalidad', models.CharField(max_length=100)),
                ('deporte', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='model.Deporte')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=200)),
                ('contrasena', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('Apellido', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('idParticipacion', models.AutoField(primary_key=True, serialize=False)),
                ('linkVideo', models.CharField(max_length=300)),
                ('deportista', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='model.Deportista')),
                ('evento', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='model.Evento')),
                ('modalidadDeporte', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='model.ModadalidadDeporte')),
                ('usuarios', models.ManyToManyField(through='model.Comentario', to='model.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DeportistaModalidad',
            fields=[
                ('idModalidadDeportista', models.AutoField(primary_key=True, serialize=False)),
                ('deportista', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='model.Deportista')),
                ('modalidad', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='model.ModadalidadDeporte')),
            ],
        ),
        migrations.AddField(
            model_name='deportista',
            name='deportista',
            field=models.ManyToManyField(default='', through='model.DeportistaModalidad', to='model.ModadalidadDeporte'),
        ),
        migrations.AddField(
            model_name='deportista',
            name='idDelegacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='model.Delegacion'),
        ),
        migrations.AddField(
            model_name='deportista',
            name='idEntrenador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='model.Entrenador'),
        ),
        migrations.AddField(
            model_name='deportista',
            name='idLugarNacimiento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='model.LugarNacimiento'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='participacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='model.Participacion'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='model.Usuario'),
        ),
    ]
