# Generated by Django 2.2.4 on 2020-02-08 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deporte',
            old_name='nombre',
            new_name='nombreDeporte',
        ),
        migrations.RemoveField(
            model_name='deportista',
            name='deportista',
        ),
        migrations.RemoveField(
            model_name='modadalidaddeporte',
            name='deporte',
        ),
        migrations.AddField(
            model_name='deportista',
            name='idModalidadDeporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.ModadalidadDeporte'),
        ),
        migrations.DeleteModel(
            name='DeportistaModalidad',
        ),
    ]
