# Generated by Django 2.2.4 on 2020-02-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20200208_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='modadalidaddeporte',
            name='idDeporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Deporte'),
        ),
    ]
