# Generated by Django 2.2.4 on 2020-02-08 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_modadalidaddeporte_iddeporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='participacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Participacion'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Usuario'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='idDelegacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Delegacion'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='idEntrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Entrenador'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='idLugarNacimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.LugarNacimiento'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Evento'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='modalidadDeporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.ModadalidadDeporte'),
        ),
    ]
