# Generated by Django 2.1 on 2020-02-08 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_usuario_user'),
        ('model', '0004_auto_20200208_0938'),
    ]

    operations = [
    ]
