# Generated by Django 2.2.4 on 2020-02-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_auto_20200208_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='deporte',
            name='icono',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
