# Generated by Django 2.2.4 on 2020-02-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_deporte_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deporte',
            name='icono',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
