# Generated by Django 2.2.4 on 2020-02-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_auto_20200208_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deporte',
            name='icono',
            field=models.ImageField(null=True, upload_to='models/static/images'),
        ),
    ]
