# Generated by Django 2.1 on 2020-02-16 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_auto_20200208_1913'),
        ('model', '0008_auto_20200208_1504'),
    ]

    operations = [
    ]
