# Generated by Django 2.2.4 on 2020-02-09 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_auto_20200208_1504'),
        ('model', '0006_auto_20200208_1913'),
    ]

    operations = [
    ]
