# Generated by Django 2.2.4 on 2020-02-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_merge_20200209_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='foto',
            field=models.ImageField(null=True, upload_to='model/static/images'),
        ),
    ]
